### ISSUE TITLE
website not loading: secure connection failed

### ISSUE THREAD

**Issue by todrobbins** [privacycg/storage-partitioning#20]
![Screen Shot 2020-12-15 at 2 21 02 PM](https://user-images.githubusercontent.com/158590/102274252-cf830a00-3ee0-11eb-8d11-49cfc0dc2b3b.png)

I've tried on a few networks with no luck. I'm not sure if it's on my end of not.

Cheers!

**Comment by annevk** [comment]
I can get to https://privacycg.github.io/storage-partitioning/ just fine. I recommend using https://downforeveryoneorjustme.com/ or some such in the future. Though note that an actual outage here would likely be a GitHub problem and not something this repository could help solve.
