### ISSUE TITLE
Ability to get localStorage value from third party iframe always blocked?

### ISSUE THREAD

**Issue by csnate** [privacycg/storage-partitioning#39]
I think this is working as intended, but the examples on https://developer.chrome.com/en/docs/privacy-sandbox/storage-partitioning/ don't really fit my example so I'll outline my use case and you can let me know if this is intended. TL;DR; - attempting to retrieve an auth token from our auth site returns undefined when trying to access localStorage from an iframe from auth site

### Prereq

- Application Site - app.example.com
- Authorization Site - auth.example.com

### Steps:

1. A user lands on auth.example.com to authenticate
2. A user successfully authenticates and auth.example.com sets a localStorage value of their auth token - `localStorage.set('token', 'a.a.a')`
3. auth.example.com then redirects the user over to app.example.com
4. app.example.com looks for a "token" in localStorage but can't find one
5. app.example.com then loads an iframe to auth.example.com/token.html and postMessage to the iframe with a message of "get-token"
6. auth.example.com/token.html receives the message and then postMessage back to the parent with a value of `localStorage.get('token')`
7. app.example.com receives "undefined" for the token from the message event

If third party storage partitioning is off, then app.example.com receives the token correctly in Step 7.

### Follow up

In practice, both the auth.example.com and app.example.com are on the same domain so we don't actually run into this problem (the token is found correctly in Step 4). However, when developing locally we use "localhost" for "app.example.com" and it is in local development where this issue is happening. Has any consideration been given to exclude "localhost" from these rules?

**Comment by annevk** [comment]
We cannot exclude `localhost` from these rules. It's used for non-developing purposes as well.

**Comment by csnate** [comment]
Cool, never hurts to ask ;)

What about the rest of the question? Is that the intention to block localStorage read access from an iframe on a third party domain when it was set by the third party domain previously?

**Comment by annevk** [comment]
Access ought to be partitioned, as per the README. If it's actually blocked (i.e., writing fails) that might be because your domain is classified as some kind of tracking domain in certain user agents.

**Comment by csnate** [comment]
Writing to localStorage isn't blocked - I can see that the token is written to localStorage on auth.example.com if I go to any page there. It's reading localStorage from auth.example.com when it's in an iframe on app.example.com. I believe this is the specific scenario outlined in point 1 of the readme here, namely "Beyond visiting, it can also allow A to infer specific state from B that depends on the user". In this case, I need A to read from B specific state about the user, namely that they have an authentication token. If that is the intention here, then I'll need to implement a different solution to get the user's token and store it on app.example.com as well.

Where can I check to see if my actual domain is listed as a tracking domain?

**Comment by johannhof** [comment]
Are you saying that localStorage isn't accessible between top-level auth.example.com and auth.example.com embedded on app.example.com? That behavior (origin- vs. site-scoped storage) is specific to Safari right now, see https://bugs.webkit.org/show_bug.cgi?id=247565

**Comment by annevk** [comment]
I was just being precise that reading nor writing is blocked. You are simply seeing different storage as a result of partitioning. If you were to get an exception then you would be blocked (and perhaps have a tracking domain).

**Comment by csnate** [comment]
@johannhof - that is what is happening and it's happening on Chrome 115. We only stared seeing it recently and randomly as only a subset of users are being opted-in to **chrome://flags/#third-party-storage-partitioning** = enabled, and developers started reporting that they weren't able to login/authenticate anymore when developing locally. 

@annevk - I'm not seeing any exceptions, only undefined for the value from `localStorage.getItem('token')`

Oddly enough, we have one other application that is on a different domain (app2.example.com) that also authenticates against auth.example.com and we saw this behavior with Safari last year, so I already have a solution in place that should work for this specific scenario as well.

Also of note, our existing solution does not work if third party cookies are disabled.

**Comment by johannhof** [comment]
@csnate to be clear, are auth.example.com and app.example.com actually cross-site in reality (i.e. different domains, like auth.com and app.com)? Then yes that's the intended effect of Storage Partitioning. Can you apply the solution you used for your other domain here as well?

**Comment by csnate** [comment]
In our specific scenario, yes - they are app.example.com and localhost. In the other scenario, they are different sub domains - app.example.com and foo.example.com. 

And thanks for the confirmation/information. I thought this was working as intended, but wanted to make sure before I went ahead with a little more complicated solution.
