### ISSUE TITLE
Accessing session storage in nested documents

### ISSUE THREAD

**Issue by NES-matsubuchi** [privacycg/storage-partitioning#42]
Our web application has a nested document structure, A1->B->A2. 
```
<html>
<body>
  A1
  <iframe src="tableau cloud URL">
    B
    <iframe src="Same domain as A1">
       A2
    </iframe>
  </iframe>
</body>
<html>
```
A1 and A2 are contents we created on AWS, and they are within the same domain. We use AWS Cognito for user authentication and store access tokens in the browser's session storage in A1. 
B is a page on Tableau's cloud. 
A2 is an HTML from AWS embedded in B, and it calls the REST API we provide on AWS using JavaScript. 
In this call, we set the access token that A1 saved in the session storage in Authorization. 

With StoragePartitioning enabled, A2 cannot access the access token from the session storage, and the REST API from A2 can no longer be called. 
Authentication using AWS Cognito and saving to the session storage are done using libraries provided by AWS, and the display in B or A2 uses features provided by Tableau, so the only part we can program is within the JavaScript in A2. 

Could you please provide a way in the JavaScript within A2 to reference the session storage saved in A1?

**Comment by NES-matsubuchi** [comment]
We are having trouble with this matter. Are there any other people who are experiencing the same issue?

**Comment by wanderview** [comment]
You should be able to use the storage partitioning deprecation trial to temporarily restore access:

https://developers.google.com/privacy-sandbox/blog/storage-partitioning-deprecation-trial

In the long term, however, you would need to change your site in some way.  Possibly requestStorageAccess to get access to non-cookie storage:

https://developer.chrome.com/blog/saa-non-cookie-storage

I am unsure if requestStorageAccess() is usable from a nested iframe like this, however.
